name: SCP Copy
description: Copy files to remote server via SSH
runs:
  using: "node16"
  main: "index.js"
inputs:
  host:
    description: 'Server host'
    required: true
  username:
    description: 'SSH username'
    required: true
  key:
    description: 'Private key'
    required: false
  password:
    description: 'Password'
    required: false
  port:
    description: 'SSH port'
    required: false
  source:
    description: 'Source files'
    required: true
  target:
    description: 'Target path on server'
    required: true
